#include <stdio.h>  
#ifdef _WINDOWS
#include <io.h>
#define isatty _isatty
#endif
void my_log(const char *frmt, const char *s = NULL);

// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
// ** Copyright UCAR (c) 1992 - 2016
// ** University Corporation for Atmospheric Research (UCAR)
// ** National Center for Atmospheric Research (NCAR)
// ** Research Applications Lab (RAL)
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
#line 2 "config_scanner.cc"

#line 4 "config_scanner.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer config_create_buffer
#define yy_delete_buffer config_delete_buffer
#define yy_flex_debug config_flex_debug
#define yy_init_buffer config_init_buffer
#define yy_flush_buffer config_flush_buffer
#define yy_load_buffer_state config_load_buffer_state
#define yy_switch_to_buffer config_switch_to_buffer
#define yyin configin
#define yyleng configleng
#define yylex configlex
#define yylineno configlineno
#define yyout configout
#define yyrestart configrestart
#define yytext configtext
#define yywrap configwrap
#define yyalloc configalloc
#define yyrealloc configrealloc
#define yyfree configfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE configrestart(configin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t configleng;

extern FILE *configin, *configout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up configtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up configtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via configrestart()), so that the user can continue scanning by
	 * just pointing configin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when configtext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t configleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow configwrap()'s to do buffer switches
 * instead of setting up a fresh configin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void configrestart (FILE *input_file  );
void config_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE config_create_buffer (FILE *file,int size  );
void config_delete_buffer (YY_BUFFER_STATE b  );
void config_flush_buffer (YY_BUFFER_STATE b  );
void configpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void configpop_buffer_state (void );

static void configensure_buffer_stack (void );
static void config_load_buffer_state (void );
static void config_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER config_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE config_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE config_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE config_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *configalloc (yy_size_t  );
void *configrealloc (void *,yy_size_t  );
void configfree (void *  );

#define yy_new_buffer config_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        configensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            config_create_buffer(configin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        configensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            config_create_buffer(configin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *configin = (FILE *) 0, *configout = (FILE *) 0;

typedef int yy_state_type;

extern int configlineno;

int configlineno = 1;

extern char *configtext;
#define yytext_ptr configtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up configtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	configleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[199] =
    {   0,
        0,    0,   41,   39,   38,   16,   31,   39,   39,   21,
       22,   26,   23,   30,   24,   39,   25,   34,   29,    1,
       28,    2,   33,   33,   17,   19,   27,   33,   33,   33,
       33,   18,   39,   20,    6,    0,   14,    0,   34,   35,
       36,   37,   35,    0,    3,    5,    4,   33,    7,   33,
       33,   33,   33,   33,   33,   15,    0,    0,   35,    0,
        0,   35,    0,    0,   12,    0,    0,   11,    0,    0,
       10,    0,    0,    8,    0,    0,    9,    0,    0,   13,
        0,   32,    0,   35,    0,    0,   35,   12,   12,   12,
       33,   11,   11,   11,   33,   10,   10,   10,   33,    8,

        8,    8,   33,    9,    9,    9,   33,   13,   13,   13,
       33,    0,   35,    0,    0,   12,    0,    0,   12,    0,
        0,   11,    0,    0,   11,    0,    0,   10,    0,    0,
       10,    0,    0,    8,    0,    0,    8,    0,    0,    9,
        0,    0,    9,    0,    0,   13,    0,    0,   13,   12,
        0,   12,    0,    0,   12,   11,    0,   11,    0,    0,
       11,   10,    0,   10,    0,    0,   10,    8,    0,    8,
        0,    0,    8,    9,    0,    9,    0,    0,    9,   13,
        0,   13,    0,    0,   13,    0,   12,    0,   11,    0,
       10,    0,    8,    0,    9,    0,   13,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    1,    6,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   21,   21,   22,   21,
       21,   21,   21,   21,   21,   21,   21,   23,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       24,    1,   25,   26,   27,    1,   28,   28,   28,   28,

       29,   28,   30,   28,   28,   28,   28,   31,   28,   32,
       28,   28,   33,   28,   28,   34,   28,   28,   28,   28,
       28,   28,   35,   36,   37,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[38] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    1,    1,    1,    1,    3,
        3,    3,    3,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    4
    } ;

static yyconst flex_int16_t yy_base[202] =
    {   0,
        0,    0,  351,  352,  352,  332,  352,  314,  342,  352,
      352,  352,  352,  352,   25,  332,   30,   28,  352,  328,
      327,  326,    0,  323,  352,  352,  352,  309,   13,   17,
      312,  352,  304,  352,  352,    0,  352,  324,   39,   33,
      352,  352,   34,   52,  352,  352,  352,    0,    0,   57,
       61,   65,   69,   73,   77,  352,  301,   79,   78,   83,
      322,  321,   45,  320,   84,   88,  319,   89,   95,  318,
       99,  102,  317,  107,  110,  316,  111,  117,  315,  122,
      292,  352,  313,  312,  104,  311,  310,  126,  116,  127,
      131,  137,  132,  138,  150,  155,  142,  154,  160,  165,

      159,  164,  170,  176,  175,  177,  188,  194,  186,  195,
      199,  309,  308,  206,  207,  198,  213,  307,  306,  214,
      218,  216,  220,  305,  304,  222,  224,  225,  229,  303,
      302,  231,  236,  227,  238,  301,  300,  240,  245,  243,
      247,  299,  298,  249,  251,  252,  256,  297,  296,  295,
      294,  293,  258,  292,  291,  290,  289,  288,  263,  287,
      286,  285,  284,  283,  264,  282,  281,  280,  279,  278,
      265,  277,  269,  254,  197,  187,  270,  181,  180,  158,
      148,  143,  271,  119,  112,   94,   90,   81,   72,   68,
       64,   60,   56,   51,   50,   44,   38,  352,  285,   42,

      287
    } ;

static yyconst flex_int16_t yy_def[202] =
    {   0,
      198,    1,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  199,  199,  198,  198,  198,  199,  199,  199,
      199,  198,  198,  198,  198,  200,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  199,  199,  199,
      199,  199,  199,  199,  199,  198,  201,  198,  198,  198,
      198,  198,  198,  198,  199,  198,  198,  199,  198,  198,
      199,  198,  198,  199,  198,  198,  199,  198,  198,  199,
      201,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      199,  198,  198,  198,  199,  198,  198,  198,  199,  198,

      198,  198,  199,  198,  198,  198,  199,  198,  198,  198,
      199,  198,  198,  198,  198,  198,  198,  198,  199,  198,
      198,  198,  198,  198,  199,  198,  198,  198,  198,  198,
      199,  198,  198,  198,  198,  198,  199,  198,  198,  198,
      198,  198,  199,  198,  198,  198,  198,  198,  199,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,    0,  198,  198,

      198
    } ;

static yyconst flex_int16_t yy_nxt[390] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   24,   25,   26,   27,   23,   23,   28,   29,
       30,   31,   23,   23,   32,   33,   34,   38,   41,   39,
       43,   51,   39,   42,   57,   53,   52,   40,   59,   44,
       54,   43,  197,   39,   58,   60,   44,   64,  197,   88,
       44,   58,   60,   61,  195,  195,   62,   44,   63,   64,
      193,   65,   66,   67,  193,   68,   69,   70,  191,   71,
       72,   73,  191,   74,   75,   76,  189,   77,   78,   79,
       83,   80,   59,   84,   86,  189,   90,   87,   65,   85,

       67,   94,   92,   68,  187,   91,   85,   70,  187,   96,
       95,   98,   91,   71,   73,  112,  100,   95,  113,  102,
       99,   74,   76,  106,  104,   77,  185,   99,  103,   79,
       89,  108,  107,  185,  110,  103,   80,  115,   90,  107,
       88,  116,  118,  111,  115,  119,   93,  114,  117,   94,
      111,   92,  122,  121,  114,  117,   97,  182,  120,  123,
      121,  124,  182,  127,  125,  120,  123,   98,  128,   96,
      127,  130,  180,  101,  131,  129,  126,  102,  134,  100,
      133,  136,  129,  126,  137,  135,  132,  133,  106,  105,
      104,  140,  135,  132,  179,  179,  139,  138,  141,  142,

      109,  176,  143,  139,  138,  141,  110,  145,  108,  146,
      148,  176,  116,  149,  145,  144,  147,  118,  151,  153,
      150,  152,  144,  147,  154,  124,  153,  155,  156,  157,
      122,  160,  158,  130,  161,  163,  162,  159,  164,  128,
      166,  134,  136,  167,  159,  168,  165,  169,  171,  172,
      170,  142,  173,  165,  174,  171,  175,  140,  178,  176,
      148,  179,  181,  180,  177,  182,  146,  184,  174,  186,
      185,  177,  187,  183,  188,  190,  192,  189,  191,  193,
      183,  194,  196,  173,  195,  197,   48,   48,   81,   81,
       81,  173,  170,  170,  168,  167,  167,  164,  164,  162,

      161,  161,  158,  158,  156,  155,  155,  152,  152,  150,
      149,  180,  143,  174,  137,  168,  131,  162,  125,  156,
      119,  150,  113,  113,   87,   87,   84,   84,   82,  109,
      105,  101,   97,   93,   89,   62,   62,   82,   40,   56,
       55,   50,   49,   47,   46,   45,   40,   37,   36,   35,
      198,    3,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static yyconst flex_int16_t yy_chk[390] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   15,   17,   15,
       18,   29,   18,   17,  200,   30,   29,   40,   43,   18,
       30,   39,  197,   39,   40,   43,   18,   63,  196,   63,
       39,   40,   43,   44,  195,  194,   44,   39,   50,   50,
      193,   50,   51,   51,  192,   51,   52,   52,  191,   52,
       53,   53,  190,   53,   54,   54,  189,   54,   55,   55,
       58,   55,   59,   58,   60,  188,   65,   60,   65,   59,

       66,   68,   66,   68,  187,   65,   59,   69,  186,   69,
       68,   71,   65,   71,   72,   85,   72,   68,   85,   74,
       71,   74,   75,   77,   75,   77,  185,   71,   74,   78,
       89,   78,   77,  184,   80,   74,   80,   89,   88,   77,
       88,   90,   91,   80,   89,   91,   93,   88,   90,   92,
       80,   92,   94,   93,   88,   90,   97,  182,   92,   94,
       93,   95,  181,   97,   95,   92,   94,   96,   98,   96,
       97,   99,  180,  101,   99,   98,   96,  100,  102,  100,
      101,  103,   98,   96,  103,  102,  100,  101,  104,  105,
      104,  106,  102,  100,  179,  178,  105,  104,  106,  107,

      109,  176,  107,  105,  104,  106,  108,  109,  108,  110,
      111,  175,  116,  111,  109,  108,  110,  114,  115,  116,
      114,  115,  108,  110,  117,  120,  116,  117,  120,  121,
      122,  123,  121,  126,  123,  127,  126,  122,  127,  128,
      129,  134,  132,  129,  122,  132,  128,  133,  134,  135,
      133,  138,  135,  128,  138,  134,  139,  140,  141,  139,
      144,  141,  145,  144,  140,  145,  146,  147,  174,  153,
      147,  140,  153,  146,  159,  165,  171,  159,  165,  171,
      146,  177,  183,  173,  177,  183,  199,  199,  201,  201,
      201,  172,  170,  169,  168,  167,  166,  164,  163,  162,

      161,  160,  158,  157,  156,  155,  154,  152,  151,  150,
      149,  148,  143,  142,  137,  136,  131,  130,  125,  124,
      119,  118,  113,  112,   87,   86,   84,   83,   81,   79,
       76,   73,   70,   67,   64,   62,   61,   57,   38,   33,
       31,   28,   24,   22,   21,   20,   16,    9,    8,    6,
        3,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int config_flex_debug;
int config_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *configtext;
#line 1 "config_scanner.ll"
#line 4 "config_scanner.ll"


////////////////////////////////////////////////////////////////////////


#define YY_NO_UNPUT 1


////////////////////////////////////////////////////////////////////////


using namespace std;

#include <iostream>

#include "vx_log.h"
#include "empty_string.h"
#include "math_constants.h"
#include "util_constants.h"
#include "is_number.h"

#include "scanner_stuff.h" //  must be included before config.tab.h
#include "threshold.h"     //  must be included before config.tab.h

#include "config.tab.h"

#include "dictionary.h"


////////////////////////////////////////////////////////////////////////


extern "C" {

   int configwrap();

}

extern int LineNumber;

extern int Column;

extern DictionaryStack * dict_stack;

extern bool is_lhs;

extern void start_string_scan  (const char *);
extern void finish_string_scan ();


////////////////////////////////////////////////////////////////////////


// static bool reading_string = false;

static bool reading_env    = false;

static YY_BUFFER_STATE file_buffer   = (YY_BUFFER_STATE) 0;

static YY_BUFFER_STATE string_buffer = 0;   //  used for string parsing

static YY_BUFFER_STATE env_buffer = 0;   //  used for environment variables outside of strings


////////////////////////////////////////////////////////////////////////


static void do_c_comment();
static void do_cpp_comment();

static  int nextchar();

static  int do_comp();

static  int do_id();

static void do_int();
static void do_float();

static void do_quoted_string();

static void patch_env(char * text);

static void get_env_text(const char * line, char * env_text, int len);

static bool do_eof();

static void do_env();

static int do_fort_thresh();


////////////////////////////////////////////////////////////////////////


#line 725 "config_scanner.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int configlex_destroy (void );

int configget_debug (void );

void configset_debug (int debug_flag  );

YY_EXTRA_TYPE configget_extra (void );

void configset_extra (YY_EXTRA_TYPE user_defined  );

FILE *configget_in (void );

void configset_in  (FILE * in_str  );

FILE *configget_out (void );

void configset_out  (FILE * out_str  );

yy_size_t configget_leng (void );

char *configget_text (void );

int configget_lineno (void );

void configset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int configwrap (void );
#else
extern int configwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( configtext, configleng, 1, configout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( configin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( configin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, (yy_size_t) max_size, configin)) == 0 && ferror(configin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(configin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int configlex (void);

#define YY_DECL int configlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after configtext and configleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! configin )
			configin = stdin;

		if ( ! configout )
			configout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			configensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				config_create_buffer(configin,YY_BUF_SIZE );
		}

		config_load_buffer_state( );
		}

	{
#line 125 "config_scanner.ll"


#line 942 "config_scanner.cc"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of configtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 352 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 127 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 128 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 129 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 130 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 132 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "config_scanner.ll"
{ return ( do_comp() ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 137 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 138 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 139 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 141 "config_scanner.ll"
{ return ( do_fort_thresh() ); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "config_scanner.ll"
{ Column+=2;   return ( LOGICAL_OP_AND ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 145 "config_scanner.ll"
{ Column+=2;   return ( LOGICAL_OP_OR  ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 147 "config_scanner.ll"
{ Column+=1;   return ( LOGICAL_OP_NOT ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 150 "config_scanner.ll"
{ ++Column;  is_lhs = false;  dict_stack->push_array();  return ( configtext[0] ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 151 "config_scanner.ll"
{ ++Column;  is_lhs = false;  dict_stack->push();        return ( configtext[0] ); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 153 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 156 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 157 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 159 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 160 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 161 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 162 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 163 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 165 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 166 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 167 "config_scanner.ll"
{ ++Column;  return ( configtext[0] ); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 171 "config_scanner.ll"
{ do_quoted_string();  return ( QUOTED_STRING ); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 173 "config_scanner.ll"
{ do_env(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 175 "config_scanner.ll"
{ return ( do_id() ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 179 "config_scanner.ll"
{ do_int();    return ( INTEGER ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 183 "config_scanner.ll"
{ do_float();  return ( FLOAT ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 190 "config_scanner.ll"
{ do_c_comment();   }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 191 "config_scanner.ll"
{ do_cpp_comment(); }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 195 "config_scanner.ll"
{ ++LineNumber;  Column = 1; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 197 "config_scanner.ll"
{ if ( do_eof() )  return ( 0 ); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 199 "config_scanner.ll"
{ ++Column; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 202 "config_scanner.ll"
ECHO;
	YY_BREAK
#line 1204 "config_scanner.cc"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed configin at a new source and called
			 * configlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = configin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( configwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * configtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of configlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					configrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			configrestart(configin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) configrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 198);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up configtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					configrestart(configin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( configwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve configtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void configrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        configensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            config_create_buffer(configin,YY_BUF_SIZE );
	}

	config_init_buffer(YY_CURRENT_BUFFER,input_file );
	config_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void config_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		configpop_buffer_state();
	 *		configpush_buffer_state(new_buffer);
     */
	configensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	config_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (configwrap()) processing, but the only time this flag
	 * is looked at is after configwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void config_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	configin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE config_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) configalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in config_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) configalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in config_create_buffer()" );

	b->yy_is_our_buffer = 1;

	config_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with config_create_buffer()
 * 
 */
    void config_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		configfree((void *) b->yy_ch_buf  );

	configfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a configrestart() or at EOF.
 */
    static void config_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	config_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then config_init_buffer was _probably_
     * called from configrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void config_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		config_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void configpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	configensure_buffer_stack();

	/* This block is copied from config_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from config_switch_to_buffer. */
	config_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void configpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	config_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		config_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void configensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)configalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in configensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)configrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in configensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE config_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) configalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in config_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	config_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to configlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       config_scan_bytes() instead.
 */
YY_BUFFER_STATE config_scan_string (yyconst char * yystr )
{
    
	return config_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to configlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE config_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) configalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in config_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = config_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in config_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	///exit( YY_EXIT_FAILURE );
  return;
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up configtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		configtext[configleng] = (yy_hold_char); \
		(yy_c_buf_p) = configtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		configleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int configget_lineno  (void)
{
        
    return configlineno;
}

/** Get the input stream.
 * 
 */
FILE *configget_in  (void)
{
        return configin;
}

/** Get the output stream.
 * 
 */
FILE *configget_out  (void)
{
        return configout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t configget_leng  (void)
{
        return configleng;
}

/** Get the current token.
 * 
 */

char *configget_text  (void)
{
        return configtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void configset_lineno (int  line_number )
{
    
    configlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see config_switch_to_buffer
 */
void configset_in (FILE *  in_str )
{
        configin = in_str ;
}

void configset_out (FILE *  out_str )
{
        configout = out_str ;
}

int configget_debug  (void)
{
        return config_flex_debug;
}

void configset_debug (int  bdebug )
{
        config_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from configlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    configin = stdin;
    configout = stdout;
#else
    configin = (FILE *) 0;
    configout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * configlex_init()
     */
    return 0;
}

/* configlex_destroy is for both reentrant and non-reentrant scanners. */
int configlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		config_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		configpop_buffer_state();
	}

	/* Destroy the stack itself. */
	configfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * configlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *configalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *configrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void configfree (void * ptr )
{
	free( (char *) ptr );	/* see configrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 201 "config_scanner.ll"




////////////////////////////////////////////////////////////////////////


int nextchar()

{

int c;


c = yyinput();

++Column;

if ( c == '\n' )  {

   ++LineNumber;

   Column = 1;

}


return ( c );

}


////////////////////////////////////////////////////////////////////////


void do_cpp_comment()

{

int c;


while ( 1 )  {

   c = nextchar();

   if ( (c == EOF) || (c == '\n') )  break;

}


return;

}


////////////////////////////////////////////////////////////////////////


void do_c_comment()

{

int c1, c2;
int comment_depth;


c1 = nextchar();
c2 = nextchar();

comment_depth = 1;

while ( 1 )  {

   if ( (c1 == EOF) || (c2 == EOF) )  break;

   if ( (c1 == '/') && (c2 == '*') )  ++comment_depth;

   if ( (c1 == '*') && (c2 == '/') )  {

      --comment_depth;

      if ( comment_depth == 0 )  break;

   }

   c1 = c2;

   c2 = nextchar();

}

   //
   //  done
   //

return;

}


////////////////////////////////////////////////////////////////////////


int do_comp()

{

int return_value;

Column += strlen(configtext);

     if ( strcmp(configtext, "<" ) == 0 )  { configlval.cval = thresh_lt;  return_value = COMPARISON; }
else if ( strcmp(configtext, ">" ) == 0 )  { configlval.cval = thresh_gt;  return_value = COMPARISON; }
else if ( strcmp(configtext, "<=") == 0 )  { configlval.cval = thresh_le;  return_value = COMPARISON; }
else if ( strcmp(configtext, ">=") == 0 )  { configlval.cval = thresh_ge;  return_value = COMPARISON; }
else if ( strcmp(configtext, "==") == 0 )  { configlval.cval = thresh_eq;  return_value = COMPARISON; }
else if ( strcmp(configtext, "!=") == 0 )  { configlval.cval = thresh_ne;  return_value = COMPARISON; }

else if ( strcmp(configtext, na_str) == 0 )  { configlval.cval = thresh_na;  return_value = NA_COMPARISON; }

else {

   return 0; ///???
}

   //
   //  done
   //

return ( return_value );

}


////////////////////////////////////////////////////////////////////////


void do_int()

{

Column += strlen(configtext);

set_int(configlval.nval, atoi(configtext));

return;

}


////////////////////////////////////////////////////////////////////////


void do_float()

{

Column += strlen(configtext);

set_double(configlval.nval, atof(configtext));

return;

}


////////////////////////////////////////////////////////////////////////


void do_quoted_string()

{

int n;
char c;
char line[max_id_length];


n = 0;

while ( 1 )  {

   c = nextchar();

   if ( c == '\"' )  break;

   if ( c == '\\' )  {

      c = nextchar();

      switch ( c )  {

         case 'n':
            line[n++] = '\n';
            break;

         case 't':
            line[n++] = '\t';
            break;

         case 'b':
            line[n++] = '\b';
            break;

         case '\"':
            line[n++] = '\"';
            break;

         case '\\':
            line[n++] = '\\';
            break;

         default:
            line[n++] = c;
            break;

      }   //  switch

   } else {

      line[n++] = c;

   }

   if ( (n + 1) >= (int) sizeof(line) )  {
     my_log("err #%s\n", "0x8408b72c");

     return;

   }

}   //  while

line[n] = (char) 0;


strncpy(configlval.text, line, sizeof(configlval.text));

configlval.text[ sizeof(configlval.text) - 1 ] = (char) 0;

patch_env(configlval.text);

   //
   //  done
   //

return;

}


////////////////////////////////////////////////////////////////////////


int do_id()

{

Column += strlen(configtext);

   //
   //  boolean?
   //

if ( strcmp(configtext, "true"  ) == 0 )  { configlval.bval = true;   return ( BOOLEAN ); }
if ( strcmp(configtext, "false" ) == 0 )  { configlval.bval = false;  return ( BOOLEAN ); }

if ( strcmp(configtext, "TRUE"  ) == 0 )  { configlval.bval = true;   return ( BOOLEAN ); }
if ( strcmp(configtext, "FALSE" ) == 0 )  { configlval.bval = false;  return ( BOOLEAN ); }

   //
   //  comparison?
   //

if ( strcmp(configtext, "lt" ) == 0 )  { configlval.cval = thresh_lt;  return ( COMPARISON ); }
if ( strcmp(configtext, "le" ) == 0 )  { configlval.cval = thresh_le;  return ( COMPARISON ); }

if ( strcmp(configtext, "gt" ) == 0 )  { configlval.cval = thresh_gt;  return ( COMPARISON ); }
if ( strcmp(configtext, "ge" ) == 0 )  { configlval.cval = thresh_ge;  return ( COMPARISON ); }

if ( strcmp(configtext, "ne" ) == 0 )  { configlval.cval = thresh_ne;  return ( COMPARISON ); }
if ( strcmp(configtext, "eq" ) == 0 )  { configlval.cval = thresh_eq;  return ( COMPARISON ); }

if ( strcmp(configtext, na_str ) == 0 )  { configlval.cval = thresh_na;  return ( NA_COMPARISON ); }

   //
   //  number?
   //

const DictionaryEntry * e = dict_stack->lookup(configtext);

if ( e && (e->is_number()) && (! is_lhs) )  {

   if ( e->type() == IntegerType )  {

      set_int(configlval.nval, e->i_value());

      return ( INTEGER ); 

   } else {

      set_double(configlval.nval, e->d_value());

      return ( FLOAT ); 

   }

}

   //
   //  nope
   //

strncpy(configlval.text, configtext, sizeof(configlval.text) - 1);

return ( IDENTIFIER );

}


////////////////////////////////////////////////////////////////////////


void patch_env(char * text)

{

int j, k, n, nn;
char c, cc;
char line[max_id_length + 1];
char env_text[max_id_length + 1];
const char * e = (const char *) 0;

memset(line, 0, sizeof(line));

strncpy(line, text, max_id_length);

memset(text, 0, max_id_length);


n = strlen(line);

k = 0;

for (j=0; j<n; ++j)  {

   c = line[j];

   if ( c == '$' )  {

      cc = line[j + 1];

      if ( cc != '{' ) text[k++] = c;
      else {

         get_env_text(line + j, env_text, sizeof(env_text));

         e = getenv(env_text);

         if ( !e )  {
           my_log("err #%s\n", "0x8b8d154c");
           
           return;
         }

         nn = strlen(e);

         if ( (k + nn) >= max_id_length )  {
           my_log("err #%s\n","0x86ea36c3");

           return;
         }

         strcpy(text + k, e);

         k += nn;

         j += strlen(env_text) + 2;   //  +3 for "${" and "}" and -1 'cuz j will get incremented at the top of the loop

      }

   } else text[k++] = c;

   if ( k >= max_id_length )  {
     my_log("err #%s\n", "0xd764c9a4");

     return;
   }

}   //  for j

   //
   //  check for any more environment variables remaining in the string
   //

if ( strstr(text, "${") )  patch_env(text);

   //
   //  done
   //

return;

}


////////////////////////////////////////////////////////////////////////


void get_env_text(const char * line, char * env_text, int len)

{

   //
   //  add 2 to skip the initial "${"
   //

const char * c = strchr(line + 2, '}');

if ( !c )  {
  my_log("err #%s\n", "0xa5877aa6");
  
  return;
}

int n = (int) (c - (line + 2));

if ( n >= len )  {
  my_log("err #%s\n", "0x10429567");

  return;
}

memset(env_text, 0, len);

strncpy(env_text, line + 2, n);


return;

}


////////////////////////////////////////////////////////////////////////


void start_string_scan(const char * s)

{

if ( empty(s) )  {
  my_log("err #%s\n", "0x10be3325");
  
  return;
}


string_buffer = config_scan_string(s);

config_switch_to_buffer(string_buffer);


return;

}


////////////////////////////////////////////////////////////////////////


void finish_string_scan()

{

config_delete_buffer(string_buffer);

string_buffer = 0;

return;

}


////////////////////////////////////////////////////////////////////////


bool do_eof()

{

if ( ! reading_env )  return ( true );

config_delete_buffer(YY_CURRENT_BUFFER);

config_switch_to_buffer(file_buffer);

reading_env = false;

Column += 3;

return ( false );

}


////////////////////////////////////////////////////////////////////////


void do_env()

{

int n;
char junk[max_id_length];
char * value = (char *) 0;



memset(junk, 0, sizeof(junk));

n = strlen(configtext);

if ( n >= (int) (sizeof(junk) - 1) )  {

   cerr << "\n\n  do_env() -> environment variable name too long\n\n";

   ///exit ( 1 );
   return;
}

strncpy(junk, configtext + 2, sizeof(junk) - 1);

junk[n - 3] = (char) 0;

value = getenv(junk);

if ( !value )  {

   cerr << "\n\n  do_env() -> can't get value of environment variable \"" << junk << "\"\n\n";

   ///exit ( 1 );
   return;
}

file_buffer = YY_CURRENT_BUFFER;

reading_env = true;

env_buffer = config_scan_string(value);

config_switch_to_buffer(env_buffer);



   //
   //  done
   //

return;

}


////////////////////////////////////////////////////////////////////////


int do_fort_thresh()

{

strncpy(configlval.text, configtext, sizeof(configlval.text));

return ( FORTRAN_THRESHOLD );

}


////////////////////////////////////////////////////////////////////////
