// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
// ** Copyright UCAR (c) 1992 - 2016
// ** University Corporation for Atmospheric Research (UCAR)
// ** National Center for Atmospheric Research (NCAR)
// ** Research Applications Lab (RAL)
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*

#include "stdio.h"
#include <string>

#include "defs.h"
#include "staticstr.h"

level_table_192_t level_table[192] = {
{  /* 0 */ "reserved",                                                             },
{  /* 1 */ "surface",                                                              },
{  /* 2 */ "cloud base",                                                           },
{  /* 3 */ "cloud top",                                                            },
{  /* 4 */ "0C isotherm",                                                          },
{  /* 5 */ "level of adiabatic condensation from sfc",                             },
{  /* 6 */ "max wind",                                                             },
{  /* 7 */ "tropopause",                                                           },
{  /* 8 */ "top of atmosphere",                                                    },
{  /* 9 */ "sea bottom",                                                           },
{  /* 10 */ "entire atmosphere",                                                   },
{  /* 11 */ "cumulonimbus base",                                                   },
{  /* 12 */ "cumulonimbus top",                                                    },
{  /* 13 */ "lowest level %g%% integrated cloud cover",                            },
{  /* 14 */ "level of free convection",                                            },
{  /* 15 */ "convection condensation level",                                       },
{  /* 16 */ "level of neutral buoyancy",                                           },
{  /* 17 */ "reserved",                                                            },
{  /* 18 */ "reserved",                                                            },
{  /* 19 */ "reserved",                                                            },
{  /* 20 */ "%g K level",                                                          },
{  /* 21 */ "reserved",                                                            },
{  /* 22 */ "reserved",                                                            },
{  /* 23 */ "reserved",                                                            },
{  /* 24 */ "reserved",                                                            },
{  /* 25 */ "reserved",                                                            },
{  /* 26 */ "reserved",                                                            },
{  /* 27 */ "reserved",                                                            },
{  /* 28 */ "reserved",                                                            },
{  /* 29 */ "reserved",                                                            },
{  /* 30 */ "reserved",                                                            },
{  /* 31 */ "reserved",                                                            },
{  /* 32 */ "reserved",                                                            },
{  /* 33 */ "reserved",                                                            },
{  /* 34 */ "reserved",                                                            },
{  /* 35 */ "reserved",                                                            },
{  /* 36 */ "reserved",                                                            },
{  /* 37 */ "reserved",                                                            },
{  /* 38 */ "reserved",                                                            },
{  /* 39 */ "reserved",                                                            },
{  /* 40 */ "reserved",                                                            },
{  /* 41 */ "reserved",                                                            },
{  /* 42 */ "reserved",                                                            },
{  /* 43 */ "reserved",                                                            },
{  /* 44 */ "reserved",                                                            },
{  /* 45 */ "reserved",                                                            },
{  /* 46 */ "reserved",                                                            },
{  /* 47 */ "reserved",                                                            },
{  /* 48 */ "reserved",                                                            },
{  /* 49 */ "reserved",                                                            },
{  /* 50 */ "reserved",                                                            },
{  /* 51 */ "reserved",                                                            },
{  /* 52 */ "reserved",                                                            },
{  /* 53 */ "reserved",                                                            },
{  /* 54 */ "reserved",                                                            },
{  /* 55 */ "reserved",                                                            },
{  /* 56 */ "reserved",                                                            },
{  /* 57 */ "reserved",                                                            },
{  /* 58 */ "reserved",                                                            },
{  /* 59 */ "reserved",                                                            },
{  /* 60 */ "reserved",                                                            },
{  /* 61 */ "reserved",                                                            },
{  /* 62 */ "reserved",                                                            },
{  /* 63 */ "reserved",                                                            },
{  /* 64 */ "reserved",                                                            },
{  /* 65 */ "reserved",                                                            },
{  /* 66 */ "reserved",                                                            },
{  /* 67 */ "reserved",                                                            },
{  /* 68 */ "reserved",                                                            },
{  /* 69 */ "reserved",                                                            },
{  /* 70 */ "reserved",                                                            },
{  /* 71 */ "reserved",                                                            },
{  /* 72 */ "reserved",                                                            },
{  /* 73 */ "reserved",                                                            },
{  /* 74 */ "reserved",                                                            },
{  /* 75 */ "reserved",                                                            },
{  /* 76 */ "reserved",                                                            },
{  /* 77 */ "reserved",                                                            },
{  /* 78 */ "reserved",                                                            },
{  /* 79 */ "reserved",                                                            },
{  /* 80 */ "reserved",                                                            },
{  /* 81 */ "reserved",                                                            },
{  /* 82 */ "reserved",                                                            },
{  /* 83 */ "reserved",                                                            },
{  /* 84 */ "reserved",                                                            },
{  /* 85 */ "reserved",                                                            },
{  /* 86 */ "reserved",                                                            },
{  /* 87 */ "reserved",                                                            },
{  /* 88 */ "reserved",                                                            },
{  /* 89 */ "reserved",                                                            },
{  /* 90 */ "reserved",                                                            },
{  /* 91 */ "reserved",                                                            },
{  /* 92 */ "reserved",                                                            },
{  /* 93 */ "reserved",                                                            },
{  /* 94 */ "reserved",                                                            },
{  /* 95 */ "reserved",                                                            },
{  /* 96 */ "reserved",                                                            },
{  /* 97 */ "reserved",                                                            },
{  /* 98 */ "reserved",                                                            },
{  /* 99 */ "reserved",                                                            },
{  /* 100 */ "%g mb",                                                              },
{  /* 101 */ "mean sea level",                                                     },
{  /* 102 */ "%g m above mean sea level",                                          },
{  /* 103 */ "%g m above ground",                                                  },
{  /* 104 */ "%g sigma level",                                                     },
{  /* 105 */ "%g hybrid level",                                                    },
{  /* 106 */ "%g m underground",                                                   },
{  /* 107 */ "%g K isentropic level",                                              },
{  /* 108 */ "%g mb above ground",                                                 },
{  /* 109 */ "PV=%g (Km^2/kg/s) surface",                                          },
{  /* 110 */ "reserved",                                                           },
{  /* 111 */ "%g Eta level",                                                       },
{  /* 112 */ "reserved",                                                           },
{  /* 113 */ "logarithmic hybrid level",                                           },
{  /* 114 */ "snow level",                                                         },
{  /* 115 */ "reserved",                                                           },
{  /* 116 */ "reserved",                                                           },
{  /* 117 */ "mixed layer depth",                                                  },
{  /* 118 */ "hybrid height level",                                                },
{  /* 119 */ "hybrid pressure level",                                              },
{  /* 120 */ "reserved",                                                           },
{  /* 121 */ "reserved",                                                           },
{  /* 122 */ "reserved",                                                           },
{  /* 123 */ "reserved",                                                           },
{  /* 124 */ "reserved",                                                           },
{  /* 125 */ "reserved",                                                           },
{  /* 126 */ "reserved",                                                           },
{  /* 127 */ "reserved",                                                           },
{  /* 128 */ "reserved",                                                           },
{  /* 129 */ "reserved",                                                           },
{  /* 130 */ "reserved",                                                           },
{  /* 131 */ "reserved",                                                           },
{  /* 132 */ "reserved",                                                           },
{  /* 133 */ "reserved",                                                           },
{  /* 134 */ "reserved",                                                           },
{  /* 135 */ "reserved",                                                           },
{  /* 136 */ "reserved",                                                           },
{  /* 137 */ "reserved",                                                           },
{  /* 138 */ "reserved",                                                           },
{  /* 139 */ "reserved",                                                           },
{  /* 140 */ "reserved",                                                           },
{  /* 141 */ "reserved",                                                           },
{  /* 142 */ "reserved",                                                           },
{  /* 143 */ "reserved",                                                           },
{  /* 144 */ "reserved",                                                           },
{  /* 145 */ "reserved",                                                           },
{  /* 146 */ "reserved",                                                           },
{  /* 147 */ "reserved",                                                           },
{  /* 148 */ "reserved",                                                           },
{  /* 149 */ "reserved",                                                           },
{  /* 150 */ "%g generalized vertical height coordinate",                          },
{  /* 151 */ "soil level %g",                                                      },
{  /* 152 */ "reserved",                                                           },
{  /* 153 */ "reserved",                                                           },
{  /* 154 */ "reserved",                                                           },
{  /* 155 */ "reserved",                                                           },
{  /* 156 */ "reserved",                                                           },
{  /* 157 */ "reserved",                                                           },
{  /* 158 */ "reserved",                                                           },
{  /* 159 */ "reserved",                                                           },
{  /* 160 */ "%g m below sea level",                                               },
{  /* 161 */ "%g m below water surface",                                           },
{  /* 162 */ "lake or river bottom",                                               },
{  /* 163 */ "bottom of sediment layer",                                           },
{  /* 164 */ "bottom of thermally active sediment layer",                          },
{  /* 165 */ "bottom of sediment layer penetrated by thermal wave",                },
{  /* 166 */ "maxing layer",                                                       },
{  /* 167 */ "bottom of root zone",                                                },
{  /* 168 */ "reserved",                                                           },
{  /* 169 */ "reserved",                                                           },
{  /* 170 */ "reserved",                                                           },
{  /* 171 */ "reserved",                                                           },
{  /* 172 */ "reserved",                                                           },
{  /* 173 */ "reserved",                                                           },
{  /* 174 */ "top surface of ice on sea, lake or river",                           },
{  /* 175 */ "top surface of ice, und snow on sea, lake or river",                 },
{  /* 176 */ "bottom surface ice on sea, lake or river",                           },
{  /* 177 */ "deep soil",                                                          },
{  /* 178 */ "reserved",                                                           },
{  /* 179 */ "top surface of glacier ice and inland ice",                          },
{  /* 180 */ "deep inland or glacier ice",                                         },
{  /* 181 */ "grid tile land fraction as a model surface",                         },
{  /* 182 */ "grid tile water fraction as a model surface",                        },
{  /* 183 */ "grid tile ice fraction on sea, lake or river as a model surface",    },
{  /* 184 */ "grid tile glacier ice and inland ice fraction as a model surface",   },
{  /* 185 */ "reserved",                                                           },
{  /* 186 */ "reserved",                                                           },
{  /* 187 */ "reserved",                                                           },
{  /* 188 */ "reserved",                                                           },
{  /* 189 */ "reserved",                                                           },
{  /* 190 */ "reserved",                                                           },
{  /* 191 */ "reserved"                                                            },
};                                                                                 
                                                                                  
