/**
(C) 2017-2018, Bad Programmer (badpr0ogrammer@gmail.com)
*/
#pragma once

#define IDSTR_ABOUT                       "About"
#define IDSTR_ABBREV                      "Abbrev"
#define IDSTR_ADD_LAYER_S                 "Add layer(s)"
#define IDSTR_ALL_CODES_AND_LEVELS        "All codes and levels"
#define IDSTR_ANIMATION                   "Animation"
#define IDSTR_ARROW_SIZE                  "Arrow size"
#define IDSTR_ARROW_WIDTH                 "Arrow width"
#define IDSTR_AT_STARTUP                  "At startup"

#define IDSTR_CHAR_SET                    "Char set"
#define IDSTR_CLOSE_ALL                   "Close all"
#define IDSTR_CLOSE_TIMESLOT              "Close timeslot"
#define IDSTR_CODE                        "Code"
#define IDSTR_CODEC                       "Codec"
#define IDSTR_COLOR                       "Color"
#define IDSTR_COMPOSE                     "Compose"
#define IDSTR_ISOLINE_PRESSURE            "Pressure isoline"
#define IDSTR_ISOLINE_TEMPERATURE         "Temperature isoline"
#define IDSTR_ISOLINE_WIND                "Wind arrows"
#define IDSTR_CONTOURS                    "Contours"
#define IDSTR_CPU_ID                      "CPU Id"

#define IDSTR_DASHED                      "Dashed"
#define IDSTR_DATA_LOADED_OPEN_Q          "Data are loaded, Open them now?"
#define IDSTR_DATA_LOADING_WIZARD         "Data loading Wizard"
#define IDSTR_DATA_SET                    "Data set"
#define IDSTR_DATE                        "Date"
#define IDSTR_DATE_TIME_DWNL              "Date_time_dwnl"
#define IDSTR_DBF_PARAMS                  "DBF-params"
#define IDSTR_DOWNLOAD                    "Download"
#define IDSTR_DOWNLOAD_GRIB2_DATA         "Download Grib2 data"
#define IDSTR_DELAY_MSEC                  "Delay, msec"

#define IDSTR_EMAIL                       "Email"
#define IDSTR_ERASE_LABEL_BKG             "Erase label bkg"

#define IDSTR_FC_FROM_C                   "FC from:"
#define IDSTR_FILE_NAME                   "File name"
#define IDSTR_FIT_ZOOM_TO_WINDOW          "Fit zoom to window"
#define IDSTR_FONT_FACE                   "Font face"
#define IDSTR_FONT_FAMILY                 "Font family"
#define IDSTR_FONT_SIZE                   "Font size"
#define IDSTR_FORECAST                    "Forecast"
#define IDSTR_FORECAST_RUN_PARAMS         "Forecast and run params"
#define IDSTR_fPS                         "fps"

#define IDSTR_GEOGRAPHIC_GRID             "Geographic grid"
#define IDSTR_GEOPOTENTIAL                "Geopotential"
#define IDSTR_GEOREFERENCING              "Georeferencing"
#define IDSTR_GO_FIRST                    "Go first"
#define IDSTR_GO_PREV                     "Go previous"
#define IDSTR_GO_NEXT                     "Go next"
#define IDSTR_GO_LAST                     "Go last"
#define IDSTR_GO_PLAY                     "Play/Stop animation"
#define IDSTR_GRIB_DATA_PLANES            "Grib data planes"
#define IDSTD_GRIB_DATA_SET               "Grib data set"
#define IDSTR_GRIB_LEVEL_PLANES           "Grib level planes"
#define IDSTR_GRIB_PALETTES               "Grib palettes"
#define IDSTR_GRIB_ABBREV                 "Grib abbrev"

#define IDSTR_HEIGHT                      "Height"

#define IDSTR_HOST                        "Host"
#define IDSTR_HPA_LEVEL                   "hPa level"

#define IDSTR_INTERFACE                   "Interface"          
#define IDSTR_INTERNAL_ERROR              "An internal error has occured."
#define IDSTR_ISOLINE                     "Isoline"
#define IDSTR_ISOLINE_STYLE               "Isoline style"

#define IDSTR_LABEL                       "Label"
#define IDSTR_LABEL_DENSITY               "Label density"
#define IDSTR_LATITUDE                    "Latitude"
#define IDSTR_LEVEL                       "Level"
#define IDSTR_LINECOLOR                   "LineColor"
#define IDSTR_LINEWIDTH                   "LineWidth"
#define IDSTR_LOAD_BY_DATE                "Load by date"
#define IDSTR_LONGITUDE                   "Longitude"
#define IDSTR_LOADING_P                   "Loading..."
#define IDSTR_LOADING_GRIB_DATA_P         "Loading GRIB data..."

#define IDSTR_MACHINE_ID_KEY              "Machine Id"
#define IDSTR_MAKE_VIDEO                  "Make video"
#define IDSTR_MENU_FILE                   "&File"
#define IDSTR_MOTHERBOARD_ID              "Motherboard Id"

#define IDSTR_NaME                        "Name"
#define IDSTR_NETWORK_PROXY               "Network Proxy"
#define IDSTR_NETWORK_ACCESS_TIMEOUT      "Network access timeout"
#define IDSTR_NO_DATA_B                   "No data !"
#define IDSTR_NO_LICENSE_KEY              "No License Key"

#define IDSTR_OPEN                        "Open"
#define IDSTR_OP_FAILED                   "Operation failed"
#define IDSTR_OP_SUCCEEDED                "Operation succeeded!"
#define IDSTR_OPTIONS                     "Options"
#define IDSTR_OR_SELECT                   " or select "

#define IDSTR_PALETTE                     "Palette"
#define IDSTR_PASSWORD                    "Password"
#define IDSTR_PLAY                        "Play"
#define IDSTR_POPUP_DWNLD_WIZARD_Q        "Popup download Wizard?"
#define IDSTR_PORT                        "Port"
#define IDSTR_PRECIPITATION               "Precipitation"
#define IDSTR_PRECIP_RATE                 "Precip.rate"
#define IDSTR_PRO_USER                    "Pro_User"
#define IDSTR_PRESSURE                    "Pressure"
#define IDSTR_PROGRAM_TERMINATED          "The program was abnormally terminated, proceed with that settings?"
#define IDSTR_PROVIDE_EMAIL_PLS           "Provide valid Email, please"

#define IDSTR_REGISTRATION                "Registration"
#define IDSTR_REGISTER_WOUT_PROXY         "Register without Proxy Server, please"
#define IDSTR_REMOVE_LAYER                "Remove layer"
#define IDSTR_RESTART_THE_PROG            "Restart the program, please"
#define IDSTR_RUN_TIME_FROM_C             "Run time from:"
#define IDSTR_RUNTIME_LAG_EXPLAIN         "Run time lag (in minutes +3h for GFS +1h for WAVE)"

#define IDSTR_SAVE_OP_SUCCEEDED           "Save operation succeeded"
#define IDSTR_SAVE_THIS_LICENSE_KEY       "Save this License Key:"
#define IDSTR_OR_SELECT_A_CITY            "or, Select a city"
#define IDSTR_SELECT_DATA_PLANES          "Select GRIB2 data planes, please"
#define IDSTR_SELECT_FILE_NAME_COLUMN     "Select file name column"
#define IDSTR_SELECT_REG_GET_FCS          "Select a Region, get a Range of Forecast Maps for Today"
#define IDSTR_SELECT_RECTANGULAR_REGION   "Select a rectangular region"
#define IDSTR_SELECT_REGION               "Select region"
#define IDSTR_SELECT_WORLD_REGION_OR      "Select world region,"
#define IDSTR_SETTINGS                    "Settings"
#define IDSTR_SIGN_IN                     "Sign In"
#define IDSTR_SIZE_BRA                    "[Size]"
#define IDSTR_SMOOTH                      "Smooth"
#define IDSTR_SMOOTH_VALUE                "Smooth value"
#define IDSTR_SPEED                       "Speed"
#define IDSTR_STARTING_ENDING_DATE        "Starting/Ending date"
#define IDSTR_STARTUP_FILES               "Startup_files"      
#define IDSTR_STEP                        "Step"

#define IDSTR_TEMPERATURE                 "Temperature"
#define IDSTR_TEXT_COLOR                  "TextColor"
#define IDSTR_TIME_SLOT                   "Time slot"
#define IDSTR_TO_C                        "to:"

#define IDSTR_UNITS                       "Units "
#define IDSTR_USER                        "User"
#define IDSTR_USER_REGISTRATION           "User Registration"
#define IDSTR_USE_MOUSE_WHELL             "Use mouse whell to zoom in/out"
#define IDSTR_UV_WIND                     "U/V Wind"

#define IDSTR_VIDEO_EXPORT                "Video export"

#define IDSTR_WEIGHT                      "Weight"
#define IDSTR_WIND_VECTORS                "Wind vectors"
#define IDSTR_WIDTH                       "Width"

#define IDSTR_YOU_ARE_LOGGED_IN           "You are already Logged in"

#define IDSTR_ZOOM                        "Zoom"
#define IDSTR_ZOOM_IN                     "Zoom in"
#define IDSTR_ZOOM_OUT                    "Zoom out"
#define IDSTR_ZOOM_TO_FIT                 "Zoom to fit"
