/**
(C) 2017-2018, Bad Programmer (badpr0ogrammer@gmail.com)
*/
#include "color_tables.h"

const char *ncl_pal_names[NCL_PAL_NUM] =
{
"BlueDarkRed18",
"BlueDarkOrange18",
"BlueGreen14",
"BrownBlue12",
"Cat12",
"GreenMagenta16",
"StepSeq25",
"amwg",
"amwg_blueyellowred",
"cosam",
"cosam12",
"hotcold_18lev",
"hotcolr_19lev",
"mch_default",
"nrl_sirkes",
"nrl_sirkes_nowhite",
"perc2_9lev",
"percent_11lev",
"posneg_1",
"posneg_2",
"prcp_1",
"prcp_2",
"prcp_3",
"precip2_15lev",
"precip2_17lev",
"precip3_16lev",
"precip4_11lev",
"precip4_diff_19lev",
"precip_11lev",
"precip_diff_12lev",
"precip_diff_1lev",
"radar",
"radar_1",
"rh_19lev",
"spread_15lev",
"sunshine_9lev",
"sunshine_diff_12lev",
"temp_19lev",
"temp_diff_18lev",
"temp_diff_1lev",
"topo_15lev",
"wgne15",
"wind_17lev",
};

char *ncl_pal_xpm[NCL_PAL_NUM] = {
":/color_tables/BlueDarkRed18.bmp",
":/color_tables/BlueDarkOrange18.bmp",
":/color_tables/BlueGreen14.bmp",
":/color_tables/BrownBlue12.bmp",
":/color_tables/Cat12.bmp",
":/color_tables/GreenMagenta16.bmp",
":/color_tables/StepSeq25.bmp",
":/color_tables/amwg.bmp",
":/color_tables/amwg_blueyellowred.bmp",
":/color_tables/cosam.bmp",
":/color_tables/cosam12.bmp",
":/color_tables/hotcold_18lev.bmp",
":/color_tables/hotcolr_19lev.bmp",
":/color_tables/mch_default.bmp",
":/color_tables/nrl_sirkes.bmp",
":/color_tables/nrl_sirkes_nowhite.bmp",
":/color_tables/perc2_9lev.bmp",
":/color_tables/percent_11lev.bmp",
":/color_tables/posneg_1.bmp",
":/color_tables/posneg_2.bmp",
":/color_tables/prcp_1.bmp",
":/color_tables/prcp_2.bmp",
":/color_tables/prcp_3.bmp",
":/color_tables/precip2_15lev.bmp",
":/color_tables/precip2_17lev.bmp",
":/color_tables/precip3_16lev.bmp",
":/color_tables/precip4_11lev.bmp",
":/color_tables/precip4_diff_19lev.bmp",
":/color_tables/precip_11lev.bmp",
":/color_tables/precip_diff_12lev.bmp",
":/color_tables/precip_diff_1lev.bmp",
":/color_tables/radar.bmp",
":/color_tables/radar_1.bmp",
":/color_tables/rh_19lev.bmp",
":/color_tables/spread_15lev.bmp",
":/color_tables/sunshine_9lev.bmp",
":/color_tables/sunshine_diff_12lev.bmp",
":/color_tables/temp_19lev.bmp",
":/color_tables/temp_diff_18lev.bmp",
":/color_tables/temp_diff_1lev.bmp",
":/color_tables/topo_15lev.bmp",
":/color_tables/wgne15.bmp",
":/color_tables/wind_17lev.bmp",
};

extern float amwg_ctbl[32][4], amwg_blueyellowred_ctbl[32][4], BkBlAqGrYeOrReViWh200_ctbl[400][4], BlAqGrYeOrRe_ctbl[200][4],
BlAqGrYeOrReVi200_ctbl[400][4], BlGrYeOrReVi200_ctbl[400][4], BlRe_ctbl[192][4], BlueDarkOrange18_ctbl[36][4],
BlueDarkRed18_ctbl[36][4], BlueGreen14_ctbl[28][4], BlueRed_ctbl[504][4], BlueRedGray_ctbl[506][4], BlueWhiteOrangeRed_ctbl[485][4],
BlueYellowRed_ctbl[508][4], BlWhRe_ctbl[202][4], BrownBlue12_ctbl[24][4], Cat12_ctbl[24][4], cosam_ctbl[20][4], cosam12_ctbl[24][4],
GreenMagenta16_ctbl[32][4], GreenYellow_ctbl[504][4], hotcold_18lev_ctbl[38][4], hotcolr_19lev_ctbl[40][4], mch_default_ctbl[30][4],
nrl_sirkes_ctbl[42][4], nrl_sirkes_nowhite_ctbl[38][4], OceanLakeLandSnow_ctbl[508][4], perc2_9lev_ctbl[20][4],
percent_11lev_ctbl[24][4], posneg_1_ctbl[37][4], posneg_2_ctbl[40][4], prcp_1_ctbl[34][4], prcp_2_ctbl[24][4], prcp_3_ctbl[46][4],
precip2_15lev_ctbl[32][4], precip2_17lev_ctbl[36][4], precip3_16lev_ctbl[34][4], precip4_11lev_ctbl[24][4],
precip4_diff_19lev_ctbl[39][4], precip_11lev_ctbl[24][4], precip_diff_12lev_ctbl[26][4], precip_diff_1lev_ctbl[4][4],
radar_ctbl[30][4], radar_1_ctbl[48][4], rh_19lev_ctbl[40][4], spread_15lev_ctbl[32][4], StepSeq25_ctbl[50][4],
sunshine_9lev_ctbl[20][4], sunshine_diff_12lev_ctbl[26][4], t2m_29lev_ctbl[60][4], tbr_240_300_ctbl[351][4],
tbr_stdev_0_30_ctbl[314][4], tbr_var_0_500_ctbl[327][4], tbrAvg1_ctbl[176][4], tbrStd1_ctbl[159][4], tbrVar1_ctbl[164][4],
temp_19lev_ctbl[40][4], temp_diff_18lev_ctbl[38][4], temp_diff_1lev_ctbl[4][4], thelix_ctbl[508][4], topo_15lev_ctbl[32][4],
ViBlGrWhYeOrRe_ctbl[194][4], wgne15_ctbl[30][4], WhBlGrYeRe_ctbl[200][4], WhiteBlue_ctbl[496][4],
WhiteBlueGreenYellowRed_ctbl[508][4], WhiteGreen_ctbl[504][4], WhiteYellowOrangeRed_ctbl[508][4], WhViBlGrYeOrRe_ctbl[202][4],
WhViBlGrYeOrReWh_ctbl[202][4], wind_17lev_ctbl[36][4], wxpEnIR_ctbl[159][4];

float(*ncl_pal_ctbl[NCL_PAL_NUM])[4] = {
BlueDarkRed18_ctbl,
BlueDarkOrange18_ctbl,
BlueGreen14_ctbl,
BrownBlue12_ctbl,
Cat12_ctbl,
GreenMagenta16_ctbl,
StepSeq25_ctbl,
amwg_ctbl,
amwg_blueyellowred_ctbl,
cosam_ctbl,
cosam12_ctbl,
hotcold_18lev_ctbl,
hotcolr_19lev_ctbl,
mch_default_ctbl,
nrl_sirkes_ctbl,
nrl_sirkes_nowhite_ctbl,
perc2_9lev_ctbl,
percent_11lev_ctbl,
posneg_1_ctbl,
posneg_2_ctbl,
prcp_1_ctbl,
prcp_2_ctbl,
prcp_3_ctbl,
precip2_15lev_ctbl,
precip2_17lev_ctbl,
precip3_16lev_ctbl,
precip4_11lev_ctbl,
precip4_diff_19lev_ctbl,
precip_11lev_ctbl,
precip_diff_12lev_ctbl,
precip_diff_1lev_ctbl,
radar_ctbl,
radar_1_ctbl,
rh_19lev_ctbl,
spread_15lev_ctbl,
sunshine_9lev_ctbl,
sunshine_diff_12lev_ctbl,
temp_19lev_ctbl,
temp_diff_18lev_ctbl,
temp_diff_1lev_ctbl,
topo_15lev_ctbl,
wgne15_ctbl,
wind_17lev_ctbl,
};


int ncl_pal_ctbl_sz[NCL_PAL_NUM] =
{
sizeof(BlueDarkRed18_ctbl) / (4 * sizeof(float)),
sizeof(BlueDarkOrange18_ctbl) / (4 * sizeof(float)),
sizeof(BlueGreen14_ctbl) / (4 * sizeof(float)),
sizeof(BrownBlue12_ctbl) / (4 * sizeof(float)),
sizeof(Cat12_ctbl) / (4 * sizeof(float)),
sizeof(GreenMagenta16_ctbl) / (4 * sizeof(float)),
sizeof(StepSeq25_ctbl) / (4 * sizeof(float)),
sizeof(amwg_ctbl) / (4 * sizeof(float)),
sizeof(amwg_blueyellowred_ctbl) / (4 * sizeof(float)),
sizeof(cosam_ctbl) / (4 * sizeof(float)),
sizeof(cosam12_ctbl) / (4 * sizeof(float)),
sizeof(hotcold_18lev_ctbl) / (4 * sizeof(float)),
sizeof(hotcolr_19lev_ctbl) / (4 * sizeof(float)),
sizeof(mch_default_ctbl) / (4 * sizeof(float)),
sizeof(nrl_sirkes_ctbl) / (4 * sizeof(float)),
sizeof(nrl_sirkes_nowhite_ctbl) / (4 * sizeof(float)),
sizeof(perc2_9lev_ctbl) / (4 * sizeof(float)),
sizeof(percent_11lev_ctbl) / (4 * sizeof(float)),
sizeof(posneg_1_ctbl) / (4 * sizeof(float)),
sizeof(posneg_2_ctbl) / (4 * sizeof(float)),
sizeof(prcp_1_ctbl) / (4 * sizeof(float)),
sizeof(prcp_2_ctbl) / (4 * sizeof(float)),
sizeof(prcp_3_ctbl) / (4 * sizeof(float)),
sizeof(precip2_15lev_ctbl) / (4 * sizeof(float)),
sizeof(precip2_17lev_ctbl) / (4 * sizeof(float)),
sizeof(precip3_16lev_ctbl) / (4 * sizeof(float)),
sizeof(precip4_11lev_ctbl) / (4 * sizeof(float)),
sizeof(precip4_diff_19lev_ctbl) / (4 * sizeof(float)),
sizeof(precip_11lev_ctbl) / (4 * sizeof(float)),
sizeof(precip_diff_12lev_ctbl) / (4 * sizeof(float)),
sizeof(precip_diff_1lev_ctbl) / (4 * sizeof(float)),
sizeof(radar_ctbl) / (4 * sizeof(float)),
sizeof(radar_1_ctbl) / (4 * sizeof(float)),
sizeof(rh_19lev_ctbl) / (4 * sizeof(float)),
sizeof(spread_15lev_ctbl) / (4 * sizeof(float)),
sizeof(sunshine_9lev_ctbl) / (4 * sizeof(float)),
sizeof(sunshine_diff_12lev_ctbl) / (4 * sizeof(float)),
sizeof(temp_19lev_ctbl) / (4 * sizeof(float)),
sizeof(temp_diff_18lev_ctbl) / (4 * sizeof(float)),
sizeof(temp_diff_1lev_ctbl) / (4 * sizeof(float)),
sizeof(topo_15lev_ctbl) / (4 * sizeof(float)),
sizeof(wgne15_ctbl) / (4 * sizeof(float)),
sizeof(wind_17lev_ctbl) / (4 * sizeof(float)),
};
